'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsBuscar
    Inherits DataSet
    
    Private tableestudiantes As estudiantesDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("estudiantes")) Is Nothing) Then
                Me.Tables.Add(New estudiantesDataTable(ds.Tables("estudiantes")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property estudiantes As estudiantesDataTable
        Get
            Return Me.tableestudiantes
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsBuscar = CType(MyBase.Clone,dsBuscar)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("estudiantes")) Is Nothing) Then
            Me.Tables.Add(New estudiantesDataTable(ds.Tables("estudiantes")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableestudiantes = CType(Me.Tables("estudiantes"),estudiantesDataTable)
        If (Not (Me.tableestudiantes) Is Nothing) Then
            Me.tableestudiantes.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsBuscar"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsBuscar.xsd"
        Me.Locale = New System.Globalization.CultureInfo("es-CR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableestudiantes = New estudiantesDataTable
        Me.Tables.Add(Me.tableestudiantes)
    End Sub
    
    Private Function ShouldSerializeestudiantes() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub estudiantesRowChangeEventHandler(ByVal sender As Object, ByVal e As estudiantesRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class estudiantesDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncarnet As DataColumn
        
        Private columnapellido1 As DataColumn
        
        Private columnapellido2 As DataColumn
        
        Private columnnombre As DataColumn
        
        Private columnsección As DataColumn
        
        Private columnestado As DataColumn
        
        Friend Sub New()
            MyBase.New("estudiantes")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property carnetColumn As DataColumn
            Get
                Return Me.columncarnet
            End Get
        End Property
        
        Friend ReadOnly Property apellido1Column As DataColumn
            Get
                Return Me.columnapellido1
            End Get
        End Property
        
        Friend ReadOnly Property apellido2Column As DataColumn
            Get
                Return Me.columnapellido2
            End Get
        End Property
        
        Friend ReadOnly Property nombreColumn As DataColumn
            Get
                Return Me.columnnombre
            End Get
        End Property
        
        Friend ReadOnly Property secciónColumn As DataColumn
            Get
                Return Me.columnsección
            End Get
        End Property
        
        Friend ReadOnly Property estadoColumn As DataColumn
            Get
                Return Me.columnestado
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As estudiantesRow
            Get
                Return CType(Me.Rows(index),estudiantesRow)
            End Get
        End Property
        
        Public Event estudiantesRowChanged As estudiantesRowChangeEventHandler
        
        Public Event estudiantesRowChanging As estudiantesRowChangeEventHandler
        
        Public Event estudiantesRowDeleted As estudiantesRowChangeEventHandler
        
        Public Event estudiantesRowDeleting As estudiantesRowChangeEventHandler
        
        Public Overloads Sub AddestudiantesRow(ByVal row As estudiantesRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddestudiantesRow(ByVal carnet As String, ByVal apellido1 As String, ByVal apellido2 As String, ByVal nombre As String, ByVal sección As String, ByVal estado As String) As estudiantesRow
            Dim rowestudiantesRow As estudiantesRow = CType(Me.NewRow,estudiantesRow)
            rowestudiantesRow.ItemArray = New Object() {carnet, apellido1, apellido2, nombre, sección, estado}
            Me.Rows.Add(rowestudiantesRow)
            Return rowestudiantesRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As estudiantesDataTable = CType(MyBase.Clone,estudiantesDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New estudiantesDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncarnet = Me.Columns("carnet")
            Me.columnapellido1 = Me.Columns("apellido1")
            Me.columnapellido2 = Me.Columns("apellido2")
            Me.columnnombre = Me.Columns("nombre")
            Me.columnsección = Me.Columns("sección")
            Me.columnestado = Me.Columns("estado")
        End Sub
        
        Private Sub InitClass()
            Me.columncarnet = New DataColumn("carnet", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncarnet)
            Me.columnapellido1 = New DataColumn("apellido1", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnapellido1)
            Me.columnapellido2 = New DataColumn("apellido2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnapellido2)
            Me.columnnombre = New DataColumn("nombre", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnnombre)
            Me.columnsección = New DataColumn("sección", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnsección)
            Me.columnestado = New DataColumn("estado", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnestado)
            Me.columncarnet.AllowDBNull = false
            Me.columnsección.ReadOnly = true
        End Sub
        
        Public Function NewestudiantesRow() As estudiantesRow
            Return CType(Me.NewRow,estudiantesRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New estudiantesRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(estudiantesRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.estudiantesRowChangedEvent) Is Nothing) Then
                RaiseEvent estudiantesRowChanged(Me, New estudiantesRowChangeEvent(CType(e.Row,estudiantesRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.estudiantesRowChangingEvent) Is Nothing) Then
                RaiseEvent estudiantesRowChanging(Me, New estudiantesRowChangeEvent(CType(e.Row,estudiantesRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.estudiantesRowDeletedEvent) Is Nothing) Then
                RaiseEvent estudiantesRowDeleted(Me, New estudiantesRowChangeEvent(CType(e.Row,estudiantesRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.estudiantesRowDeletingEvent) Is Nothing) Then
                RaiseEvent estudiantesRowDeleting(Me, New estudiantesRowChangeEvent(CType(e.Row,estudiantesRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveestudiantesRow(ByVal row As estudiantesRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class estudiantesRow
        Inherits DataRow
        
        Private tableestudiantes As estudiantesDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableestudiantes = CType(Me.Table,estudiantesDataTable)
        End Sub
        
        Public Property carnet As String
            Get
                Return CType(Me(Me.tableestudiantes.carnetColumn),String)
            End Get
            Set
                Me(Me.tableestudiantes.carnetColumn) = value
            End Set
        End Property
        
        Public Property apellido1 As String
            Get
                Try 
                    Return CType(Me(Me.tableestudiantes.apellido1Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("No se puede obtener el valor porque es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableestudiantes.apellido1Column) = value
            End Set
        End Property
        
        Public Property apellido2 As String
            Get
                Try 
                    Return CType(Me(Me.tableestudiantes.apellido2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("No se puede obtener el valor porque es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableestudiantes.apellido2Column) = value
            End Set
        End Property
        
        Public Property nombre As String
            Get
                Try 
                    Return CType(Me(Me.tableestudiantes.nombreColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("No se puede obtener el valor porque es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableestudiantes.nombreColumn) = value
            End Set
        End Property
        
        Public Property sección As String
            Get
                Try 
                    Return CType(Me(Me.tableestudiantes.secciónColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("No se puede obtener el valor porque es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableestudiantes.secciónColumn) = value
            End Set
        End Property
        
        Public Property estado As String
            Get
                Try 
                    Return CType(Me(Me.tableestudiantes.estadoColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("No se puede obtener el valor porque es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableestudiantes.estadoColumn) = value
            End Set
        End Property
        
        Public Function Isapellido1Null() As Boolean
            Return Me.IsNull(Me.tableestudiantes.apellido1Column)
        End Function
        
        Public Sub Setapellido1Null()
            Me(Me.tableestudiantes.apellido1Column) = System.Convert.DBNull
        End Sub
        
        Public Function Isapellido2Null() As Boolean
            Return Me.IsNull(Me.tableestudiantes.apellido2Column)
        End Function
        
        Public Sub Setapellido2Null()
            Me(Me.tableestudiantes.apellido2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsnombreNull() As Boolean
            Return Me.IsNull(Me.tableestudiantes.nombreColumn)
        End Function
        
        Public Sub SetnombreNull()
            Me(Me.tableestudiantes.nombreColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IssecciónNull() As Boolean
            Return Me.IsNull(Me.tableestudiantes.secciónColumn)
        End Function
        
        Public Sub SetsecciónNull()
            Me(Me.tableestudiantes.secciónColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsestadoNull() As Boolean
            Return Me.IsNull(Me.tableestudiantes.estadoColumn)
        End Function
        
        Public Sub SetestadoNull()
            Me(Me.tableestudiantes.estadoColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class estudiantesRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As estudiantesRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As estudiantesRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As estudiantesRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
